spring.application.name=SpringBoot-BackEnd


spring.datasource.url=jdbc:mysql://localhost:3306/jwt
spring.datasource.username=root
spring.datasource.password=abc#ABC#307
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
#gemini.text-model=gemini-2.5-flash
#gemini.embedding-model=gemini-embedding-001


#gemini.api-key=??????
#
## The standard, highly available free-tier text model
#gemini.text-model:gemini-3.5-flash
#
## The correct official name for the embedding model
#gemini.embedding-model=text-embedding-004

